apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
  labels:
    name: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingressDep
  template:
    metadata:
      labels:
        app: ingressDep
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      containers:
        - name: ingresscon
          image: "gcr.io/kyle-server-402706/ingress-go:latest"
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
            - name: tcp
              containerPort: 9001
              hostPort: 9001
          volumeMounts:
            - mountPath: /data
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: hostpath-pvc

            # command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
            # command: ["/bin/app", "-c", "while true; do sleep 3600; done"]
            # command: ["/bin/sh", "-c"]
            # args:
            #   ["while true; do sleep 3600; done"]
            # resources:
            #   requests: # 요청 리소스: 최소 필요한 양
            #     memory: "32Mi"
            #     cpu: "200m"
            #   limits: # 리소스 제한: 최대 허용 양
            #     memory: "64Mi"
            #     cpu: "400m"
