apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-node-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-node
  template:
    metadata:
      labels:
        app: chat-node
    spec:
      containers:
        - name: chat-node-client
          image: 'me-west1-docker.pkg.dev/kyle-server-402706/kyle-registry/chat-node-client:latest'
          ports:
            - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: chat-node-client
spec:
  type: ClusterIP
  selector:
    app: chat-node
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
