apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-tools-app-server-deployment
  labels:
    app: blockchain-tools-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-tools-app
  template:
    metadata:
      labels:
        app: blockchain-tools-app
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: service-pool
      containers:
        - name: blockchain-tools-app-block-timestamp
          image: 'me-west1-docker.pkg.dev/kyle-server-402706/kyle-registry/block-timestamp-app-server:latest'
          ports:
            - protocol: TCP
              containerPort: 8080
          # pvc
          volumeMounts:
            - mountPath: /data
              name: data-volume
        - name: blockchain-tools-app-transfer-tracker
          image: 'me-west1-docker.pkg.dev/kyle-server-402706/kyle-registry/transfer-tracker-app-server:latest'
          ports:
            - protocol: TCP
              containerPort: 8081
          # pvc
          volumeMounts:
            - mountPath: /data
              name: data-volume2
      # pvc
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: timestamp-pvc
        - name: data-volume2
          persistentVolumeClaim:
            claimName: tracker-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-tools-app-server-service
  labels:
    app: blockchain-tools-app
spec:
  type: ClusterIP
  selector:
    app: blockchain-tools-app
  ports:
    - name: block-timestamp-service
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: transfer-tracker-service
      protocol: TCP
      port: 8081
      targetPort: 8081
