apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timestamp-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
