apiVersion: v1
kind: Pod
metadata:
  name: command-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['/bin/sh', '-c']
      args:
        - |
          echo "Starting first command"; \
          echo "Running second command"; \
          echo "All commands executed!"; \
          sleep 3600
