apiVersion: v1
kind: Pod
metadata:
  name: multi-port-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
