apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-envoy
          image: 'me-west1-docker.pkg.dev/kyle-server-402706/kyle-registry/chat-envoy:latest'
          ports:
            - protocol: TCP
              containerPort: 8080
