apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-server-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
