---
apiVersion: v1
kind: Service
metadata:
  name: dexserv
  labels:
    app: dexserv
spec:
  type: ClusterIP
  selector:
    app: dexDep
  ports:
    - name: tcp
      port: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: dex
#   labels:
#     app: dex
# spec:
#   type: ClusterIP
#   selector:
#     app: dexDep
#   ports:
#     - port: 8080
#       targetPort: 8080

