apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-tcp-app-server-deployment
  labels:
    app: db-tcp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-tcp-app
  template:
    metadata:
      labels:
        app: db-tcp-app
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: service-pool
      containers:
        - name: postgres
          image: 'postgres:latest'
          ports:
            - protocol: TCP
              containerPort: 5432
          # postgres passwoard
          env:
            - name: POSTGRES_PASSWORD
              value: 1q2w3e4r
          # pvc
          volumeMounts:
            - mountPath: /data
              name: postgres-data-volume
        - name: redis
          image: 'redis:latest'
          ports:
            - protocol: TCP
              containerPort: 6379
          # pvc
          volumeMounts:
            - mountPath: /data
              name: redis-data-volume
      # pvc
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: db-postgres-pvc
        - name: redis-data-volume
          persistentVolumeClaim:
            claimName: db-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-tcp-app-server-service
  labels:
    app: db-tcp-app
spec:
  type: ClusterIP
  selector:
    app: db-tcp-app
  ports:
    - name: db-postgres-service
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: db-redis-service
      protocol: TCP
      port: 6379
      targetPort: 6379
