apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orakle-btcfi-backend-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
