---
apiVersion: v1
kind: Service
metadata:
  name: d1-service
  namespace: default
  labels:
    name: apa000dep
spec:
  type: NodePort
  selector:
    app: apa000kube
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 3001
      targetPort: 443
      nodePort: 30443
