apiVersion: v1
kind: Service
metadata:
  name: ingress-reverse-proxy-service
spec:
  type: ClusterIP
  selector:
    app: ingress-reverse-proxy-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
